### ISSUE TITLE
Add documentation for using CRTM to post-process synthetic satellite

### ISSUE THREAD

**Issue by hertneky** [ufs-community/ufs-srweather-app#151]
## Description
Add documentation on how the user will download, stage and use the CRTM fix files for outputting synthetic satellite products via UPP. This capability is not currently in the SRW and an issue to add it to the regional workflow has been created.

## Related to (optional)
https://github.com/NOAA-EMC/regional_workflow/issues/543

**Comment by gspetro-NOAA** [comment]
@MichaelLueken It seems like we have documentation [here](https://ufs-srweather-app.readthedocs.io/en/latest/UsersGuide/CustomizingTheWorkflow/InputOutputFiles.html#id4), but the [regional_workflow issue](https://github.com/ufs-community/regional_workflow/issues/543) may be broader than just documentation. Do you think this should be closed?

**Comment by MichaelLueken** [comment]
@gspetro-NOAA From issue [#543](https://github.com/ufs-community/regional_workflow/issues/543) in regional_workflow, PR [#682](https://github.com/ufs-community/regional_workflow/pull/682) was opened in regional_workflow to add the necessary `USE_CRTM` and `CRTM_DIR` components in `exregional_run_post.sh`, `config_defaults.yaml`, `setup.py`, and `valid_param_vals.yaml`.  The documentation that is currently available should be sufficient to close this issue (since it describes downloading CRTM coefficients and setting the necessary `USE_CRTM` and `CRTM_DIR` variables).
