### ISSUE TITLE
Allow the ufs-weather-model build to use the ufs_common module

### ISSUE THREAD

**Issue by JeffBeck-NOAA** [ufs-community/ufs-srweather-app#154]
## Description
The current environment files in the SRW App use individual module loads instead of the new "ufs_common" module in ufs-weather-model.  This feature will add the ability to source the "ufs_common" module and remove most individual module loads.

## Solution
```
module use ${SR_WX_APP_TOP_DIR}/src/ufs-weather-model/modulefiles
module load ufs_common
```
where SR_WX_APP_TOP_DIR is defined by the user or included in the devbuild.sh script as the current directory.

## Related to (optional)
Related to PR #152.

**Comment by MichaelLueken** [comment]
@JeffBeck-NOAA - The use of `srw_common`, rather than loading all common libraries per modulefile, was brought in with PR #200.  The `srw_common.lua` file has since been updated to the point that, so long as the associated spack-stack version has been built on a given platform, the SRW will properly build.  I'm checking to see if this issue can be closed.

**Comment by MichaelLueken** [comment]
Closing issue now.  If you feel this issue hasn't been addressed, please feel free to either reopen this issue or open a new issue.
