### ISSUE TITLE
Incorrect documentation in Step 4 of https://github.com/ufs-community/ufs-srweather-app/wiki/Getting-Started

### ISSUE THREAD

**Issue by benjamin-cash** [ufs-community/ufs-srweather-app#16]
The documentation in Step 4 for running the model directs the user to: 
cd ufs-srweather-app/../expt_dirs/$EXPT_SUBDIR

However, on Cheyenne EXPTDIR="/glade/work/bcash/expt_dirs/test_community".

**Comment by jwolff-ncar** [comment]
@JulieSchramm Can you please update this? Thanks!

**Comment by jwolff-ncar** [comment]
I think if we just change this to be cd EXPTDIR that would cover all platforms since EXPTDIR=/path-to/ufs-srweather-app/../expt_dirs/${EXPT_SUBDIR}. @JulieSchramm do you agree? If so, would you change the necessary documentation on the wiki (and UG). Please update this issue as changes are made. Thanks!

**Comment by JulieSchramm** [comment]
Changed in wiki and in UG pr #78
