### ISSUE TITLE
regional_workflow/scripts/exregional_make_orog.sh orography filtering

### ISSUE THREAD

**Issue by sentientc** [ufs-community/ufs-srweather-app#162]
# Description(ufs-v1.0.0 )
I was trying to find out why my run will ended with at 47th hours and found this.
filter_topo will not run as the namelist file have refine_ratio that is not in filter_topo program
line 458ish
cat > "${filter_dir}/input.nml" <<EOF
&filter_topo_nml
  grid_file = "${mosaic_fp}"
  topo_file = "${filtered_orog_fp_prefix}"
  mask_field = "land_frac"
  regional = .true.
  refine_ratio = ${refine_ratio}
  stretch_fac = ${STRETCH_FAC}
  res = ${res}
/
EOF
## Steps to Reproduce

use the workflow to generate any case
log from run_make_orog.sh will have this error

## Additional Context
this probably not a compiler issue 

## Output
1. comment out line 481ish "cp ../../input.nml ." because refine_ratio is not in filter_topo namelist
Unknown Error Error reading input.nml
2. comment out line 481ish refine_ratio
no error

**Comment by MichaelLueken** [comment]
Hello @sentientc,

I'm going through and checking if issues that have been open for several years have been addressed and can be closed, or are still problematic.  Looking at the [scripts/exregional_make_orog.sh](https://github.com/ufs-community/ufs-srweather-app/blob/develop/scripts/exregional_make_orog.sh) script in the current develop branch, the `refine_ratio` namelist parameter is no longer present.  Looking at the current namelist information for `filter_topo_nml`:
```
namelist /filter_topo_nml/ topo_file, topo_field, mask_field, grid_file, zero_ocean, &
        stretch_fac, res, nested, grid_type, regional
```
`refine_ratio` isn't part of the namelist options.  Since this namelist variable has been removed, can this issue be closed?  Thank you very much for your time.
