### ISSUE TITLE
Quick fix to cheyenne staged data location for config.community.sh

### ISSUE THREAD

**Issue by padhrigmccarthy** [ufs-community/ufs-srweather-app#259]
# Description

Path is incorrect to staged data on cheyenne in the develop instructions for running config.community.sh .

## Steps to Reproduce

1. View develop docs at: https://ufs-srweather-app.readthedocs.io/en/develop/BuildRunSRW.html#download-and-stage-the-data
3. Path to staged data is shown as: /glade/p/ral/jntp/UFS_SRW_app/staged_extrn_mdl_files
4. Path to staged data should be: /glade/p/ral/jntp/UFS_SRW_App/develop/staged_extrn_mdl_files/FV3GFS/ (not sure whether the "FV3GFS" is required or not -- it used to be)

## Additional Context

This may only be relevant for those attempting to run config.community.sh on cheyenne, but those are probably the beginners (like me) who could get derailed by some small detail like this.

## Output

None.

**Comment by gspetro-NOAA** [comment]
@padhrigmccarthy Thanks for this--I'll add a clarification to the docs. The paths listed are just the base paths. These paths can (and should) be followed by a subdirectory such as "FV3GFS." However, there are several options available (e.g., "HRRR," "RAP"), which is why only the base path is provided.

**Comment by mkavulich** [comment]
@gspetro-NOAA note that the paths have not been updated in the documentation since I standardized the staged data across platforms, many of the static data paths are in different locations compared to the previous release. For example on Cheyenne, /glade/p/ral/jntp/UFS_SRW_app/staged_extrn_mdl_files --> /glade/p/ral/jntp/UFS_SRW_**App/develop**/staged_extrn_mdl_files

**Comment by gspetro-NOAA** [comment]
@mkavulich Yes, I was waiting to include the updates for the v2 release, but it makes sense to make the changes now for develop. I'll add that to my current PR as well.

**Comment by mkavulich** [comment]
@gspetro-NOAA Thanks!

**Comment by mkavulich** [comment]
This was resolved some time ago.
