### ISSUE TITLE
CI test runs unexpectedly on personal fork

### ISSUE THREAD

**Issue by gsketefian** [ufs-community/ufs-srweather-app#265]
# Description

Received email from github alerting me to a failed test for a push to the `develop` branch on my personal fork that I don't remember making.  Not sure what is going on.

## Steps to Reproduce
Don't know.

## Additional Context
See screenshot of the test report below.

<img width="1506" alt="CI_report" src="https://user-images.githubusercontent.com/31046882/169420277-21a23eab-0108-45d8-8ded-e5116f62f019.png">

**Comment by gsketefian** [comment]
@jessemcfarland Do you think this is related to PR #253?

**Comment by jessemcfarland** [comment]
No, this looks like a GitHub actions job that timed out waiting for an available runner. #253 enabled the Jenkins pipeline, which is independent of GitHub actions.

**Comment by MichaelLueken** [comment]
@gsketefian - It sounds like you were concerned that GitHub Actions were launched when you didn't update your fork's develop branch.  I can see that the PR #258 was merged into develop on May 18th.  I'm unsure why this update to the authoritative repository would have been brought into your fork's develop branch without you syncing your develop branch.  From work done on the GSI, if an update was applied directly to the authoritative develop branch that alters history from commits that currently exist in forked repositories, then it will force the update into those forked branches, but that shouldn't be the case here.

From PR #412, it sounds like the `build.yml` GHA failed regularly, before it was ultimately removed in 412.

If you are concerned that GitHub Actions are being run in branches within forks, they need to be run for develop and release branches, whether authoritative or forked.  In PR #412, the GitHub Actions were updated to only run for develop and releases branches (both pushes and pull requests to), rather than run for every push to all branches.

If this issue was opened due to testing when you didn't sync develop yourself, I don't think there is anything that can be done.  If this issue was opened because testing was done in a forked repository, this is a requirement and will not be changed.

**Comment by gsketefian** [comment]
@MichaelLueken Did you mean to send this message to someone else (Jesse?)?

**Comment by MichaelLueken** [comment]
@gsketefian Since you originally opened this issue, I just wanted to see if it would be alright to close it.  If you are okay with closing the issue, I will take care of it.

**Comment by gsketefian** [comment]
@MichaelLueken Ok, I see.  Thanks for asking.  I don't remember the details since it was a long time ago, and i haven't experienced similar issues in a long time, so this was probably fixed somewhere along the way.  Please feel free to close it.  Thanks!

**Comment by MichaelLueken** [comment]
Thanks for the confirmation, @gsketefian!  Closing issue now.
