### ISSUE TITLE
Request for 2019061518 12-hour fcst HRRR/RAP Data on Level 1 Systems 

### ISSUE THREAD

**Issue by gspetro-NOAA** [ufs-community/ufs-srweather-app#551]
## Description

I am creating a Tutorial Chapter for the SRW App documentation and need the corresponding data to be added to the Level 1 platforms. EPIC/AUS does not yet have the permissions to do this on all Level 1 platforms. 

The first tutorial mirrors the GST/short course case and changes the physics in the out-of-the-box `config.community.yaml` case to `FV3_RRFS_v1beta`. With this, users need to change the data to HRRR ICs and RAP LBCs, which are available in `/contrib/EPIC/UFS_SRW_App/v2p1/input_model_data/` on AWS/NOAA Cloud and in @EdwardSnyder-NOAA's personal directory on Jet (`/lfs4/HFIP/hfv3gfs/Edward.Snyder/new-srw-dev-rufs/rufs-git/utestdir/community/`). However, these data are not available across Level 1 platforms in a standardized location. 

## Solution
Add HRRR/RAP hourly data for the forecast to the appropriate `UFS_SRW_App/develop/input_model_data/` subdirectories. 

## Requirements**
The following forecast data must appear on all supported Level 1 platforms (RDHPCS & NOAA Cloud) in the standardized directory locations:
    - hrrr.t18z.wrfprsf00.grib2 
    - rap.t18z.wrfnatf01.grib2    
    - rap.t18z.wrfnatf02.grib2    
    - rap.t18z.wrfnatf03.grib2    
    - rap.t18z.wrfnatf04.grib2  
    - rap.t18z.wrfnatf05.grib2
    - rap.t18z.wrfnatf06.grib2
    - rap.t18z.wrfnatf07.grib2
    - rap.t18z.wrfnatf08.grib2
    - rap.t18z.wrfnatf09.grib2
    - rap.t18z.wrfnatf10.grib2
    - rap.t18z.wrfnatf11.grib2
    - rap.t18z.wrfnatf12.grib2

Additionally, the data must be uploaded to the SRW App S3 data bucket.

## Acceptance Criteria (Definition of Done)
Required forecast data appears on all supported Level 1 platforms (RDHPCS & NOAA Cloud) and in the SRW App S3 data bucket.

**Comment by mkavulich** [comment]
@gspetro I can take care of this on Jet, Hera, Orion, and Cheyenne. But we will need to decide on the best way to stage this data: currently, the data directories that you pointed on Jet (/lfs4/HFIP/hfv3gfs/Edward.Snyder/new-srw-dev-rufs/rufs-git/utestdir/community/) are organized differently than the directory structures for existing staged data (data on disk is currently `MODELNAME/forecast_datetime/files` (or for FV3GFS, `MODELNAME/file_format/forecast_datetime/files`). Would it be okay if I rearrange the new data to fit the existing directory structure? That would be my preference.

Additionally, we will need to figure out what to do with ensemble data (GDAS and GEFS). Since data files from different ensemble members for the valid time and forecast time have the same file names, we will either need to change the filenames (e.g. gdas.t00z.atmf006.nc.mem1, gdas.t00z.atmf006.nc.mem2, etc) or put them in a subdirectory structure based on members (e.g. MODELNAME/forecast_datetime/member/files). I'm open to either option but we'll just need to make a decision and stick to it.

Edit: I got a bit ahead of myself and I forgot that you are only wanting to stage the RAP and HRRR data, not the ensemble data. So I guess ignore that last half, though it is an interesting question for the future.

**Comment by gspetro-NOAA** [comment]
@mkavulich Thanks! My hope was that the data could be placed in the standardized locations (which is what I point to in my PR #556 ). The only reason it's in Eddie's directory in Jet is because we didn't have access to add the data to the standardized location, but I needed it somewhere for testing purposes. 

As to the ensemble stuff, it seems like maybe that could be a good topic for discussion at tomorrow's CM meeting? Tagging @MichaelLueken

**Comment by MichaelLueken** [comment]
@gspetro-NOAA @mkavulich Thanks for the idea!  I have added the ensemble discussion to tomorrow's CM meeting.

**Comment by mkavulich** [comment]
@gspetro-NOAA I have staged the data on Jet, Hera, and Cheyenne; Orion is down for maintenance today so I'll have to take care of that later. Let me know if anything looks incorrect.

**Comment by gspetro-NOAA** [comment]
@mkavulich Great, thanks! We will take care of the data for Gaea and NOAA Cloud on our end.

**Comment by gspetro-NOAA** [comment]
Update: I have moved data to standardized locations on AWS, GCP, and Azure. Still working Gaea and the SRW S3 bucket.

**Comment by EdwardSnyder-NOAA** [comment]
Data is now in the S3 bucket: 
https://noaa-ufs-srw-pds.s3.amazonaws.com/index.html#input_model_data/HRRR/2019061518/
https://noaa-ufs-srw-pds.s3.amazonaws.com/index.html#input_model_data/RAP/2019061518/

**Comment by gspetro-NOAA** [comment]
And data for Gaea has also been staged! :)
@MichaelLueken It looks like this issue is ready to be closed?

**Comment by MichaelLueken** [comment]
@gspetro-NOAA Sure!  It looks like the necessary data has been staged across the Tier-1 machines, so I will go ahead and close this issue.  Thanks!

**Comment by mkavulich** [comment]
Just for posterity's sake, I did finally get around to putting the new data on Orion as well.
